" ~/.vim/sessions/default.vim:
" Vim session script.
" Created by session.vim 2.7 on 23 June 2015 at 23:02:24.
" Open this file in Vim and run :source % to restore your session.

set guioptions=egmrL
silent! set guifont=PowerlineSymbols\ for\ Powerline
if exists('g:syntax_on') != 1 | syntax on | endif
if exists('g:did_load_filetypes') != 1 | filetype on | endif
if exists('g:did_load_ftplugin') != 1 | filetype plugin on | endif
if exists('g:did_indent_on') != 1 | filetype indent on | endif
if &background != 'light'
	set background=light
endif
if !exists('g:colors_name') || g:colors_name != 'macvim' | colorscheme macvim | endif
call setqflist([])
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
cd ~/
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +1 neutron_yield_eng.tex
badd +1 ldjtheme.sty
badd +15 Desktop/iwork/ctex_ppt_ldj_template/ldj_ppt_template.tex
badd +1 Desktop/iwork/ctex_ppt_ldj_template/ldjtheme.sty
badd +1 Desktop/iwork/WS3.25_isotopes/Isotope_progress.tex
badd +1 Desktop/iwork/WS3.25_isotopes/ldjtheme.sty
badd +10 Desktop/iwork/WG5.21Model_independent/model_independent_estimation_of_fn.tex
badd +1 Desktop/iwork/WG5.21Model_independent/ldjtheme.sty
badd +1 neutron_yield_eng.log
badd +763 Desktop/iwork/WS3.25_isotopes/Isotope_progress.log
badd +73 neutron_yield_eng.aux
badd +33 Library/Mobile\ Documents/com~apple~CloudDocs/iwork/neutron_yield/neutron_yield_eng.tex
badd +1 Library/Mobile\ Documents/com~apple~CloudDocs/iwork/neutron_yield/ldjtheme.sty
badd +1 Library/Mobile\ Documents/com~apple~CloudDocs/iwork/neutron_yield/neutron_yield_technote.tex
badd +149 Library/Mobile\ Documents/com~apple~CloudDocs/iBlog/ldengjie.github.io/_posts/blog/2014-07-01-compile-gcc.md
badd +1914 Library/Mobile\ Documents/com~apple~CloudDocs/iwork/neutron_yield/neutron_yield_eng.log
argglobal
silent! argdel *
argadd Library/Mobile\ Documents/com~apple~CloudDocs/iwork/neutron_yield/neutron_yield_eng.tex
edit Library/Mobile\ Documents/com~apple~CloudDocs/iwork/neutron_yield/neutron_yield_technote.tex
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winheight=1 winwidth=1
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=4
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
3,23fold
32,33fold
34,35fold
36,39fold
44,76fold
80,83fold
40,87fold
186,193fold
201,206fold
210,215fold
194,217fold
185,217fold
227,233fold
222,234fold
239,252fold
257,260fold
235,263fold
268,281fold
286,289fold
264,292fold
297,302fold
308,321fold
293,322fold
218,322fold
328,331fold
346,411fold
326,414fold
416,419fold
433,457fold
415,459fold
324,459fold
89,459fold
461,462fold
465,466fold
467,468fold
469,473fold
460,473fold
479,498fold
500,519fold
522,539fold
474,540fold
545,567fold
541,570fold
575,579fold
581,585fold
587,591fold
571,597fold
598,602fold
603,616fold
3
normal! zc
32
normal! zc
34
normal! zc
36
normal! zc
40
silent! normal! zo
44
normal! zc
80
normal! zc
40
normal! zc
89
silent! normal! zo
185
silent! normal! zo
186
normal! zc
194
silent! normal! zo
201
normal! zc
210
normal! zc
194
normal! zc
185
normal! zc
218
silent! normal! zo
222
silent! normal! zo
227
normal! zc
222
normal! zc
235
silent! normal! zo
239
normal! zc
257
normal! zc
235
normal! zc
264
silent! normal! zo
268
normal! zc
286
normal! zc
264
normal! zc
293
silent! normal! zo
297
normal! zc
308
normal! zc
293
normal! zc
218
normal! zc
324
silent! normal! zo
326
silent! normal! zo
328
normal! zc
346
normal! zc
326
normal! zc
415
silent! normal! zo
416
normal! zc
433
normal! zc
415
normal! zc
324
normal! zc
89
normal! zc
460
silent! normal! zo
461
normal! zc
465
normal! zc
467
normal! zc
469
normal! zc
460
normal! zc
474
silent! normal! zo
479
normal! zc
500
normal! zc
522
normal! zc
474
normal! zc
541
silent! normal! zo
545
normal! zc
541
normal! zc
571
silent! normal! zo
575
normal! zc
581
normal! zc
587
normal! zc
571
normal! zc
598
normal! zc
603
normal! zc
let s:l = 618 - ((578 * winheight(0) + 25) / 51)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
618
normal! 0
tabnext 1
if exists('s:wipebuf')
"   silent exe 'bwipe ' . s:wipebuf
endif
" unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToO
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save

" Support for special windows like quick-fix and plug-in windows.
" Everything down here is generated by vim-session (not supported
" by :mksession out of the box).

1wincmd w
tabnext 1
if exists('s:wipebuf')
  if empty(bufname(s:wipebuf))
if !getbufvar(s:wipebuf, '&modified')
  let s:wipebuflines = getbufline(s:wipebuf, 1, '$')
  if len(s:wipebuflines) <= 1 && empty(get(s:wipebuflines, 0, ''))
    silent execute 'bwipeout' s:wipebuf
  endif
endif
  endif
endif
doautoall SessionLoadPost
unlet SessionLoad
" vim: ft=vim ro nowrap smc=128
